### ISSUE TITLE
Does not work with CRA v3

### ISSUE THREAD

**Issue by wildlifehexagon** [packtracker/webpack-plugin#13]
This looks like a really nice tool and I would love to use it with my `create-react-app` projects, but it seems that's not possible with CRA v3. The `--stats` flag for generating builds was removed a while back (see [here](https://github.com/facebook/create-react-app/issues/6904)) so `bundle-stats.json` is not generated. Is there a different way to use this with CRA (without ejecting)?

**Comment by jondavidjohn** [comment]
We actually support all versions of CRA now with our GitHub Action or the CircleCI Orb!

https://docs.packtracker.io/uploading-your-webpack-stats/common-app-platforms/create-react-app#for-circleci-or-github-actions-users

**Comment by wildlifehexagon** [comment]
I tried using a similar GitHub workflow but it errors out. Here's my config file:

```
on: pull_request
name: bundle analyzer
jobs:
  packtracker:
    name: report webpack stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: report webpack stats
        uses: packtracker/report@2.2.7
        env:
          PT_PROJECT_TOKEN: ${{ secrets.PT_PROJECT_TOKEN }}
```

In the logs, here's what I see:

```
Detected Create React App ("^3.2.0")
? Are you sure you want to eject? This action is permanent. (y/N) ? Are you sure you want to eject? This action is permanent. (y/N) y? Are you sure you want to eject? This action is permanent. Yes
y
y
y
```

The "y" presses continue for 20,000+  times before it just errors out. Am I overlooking something in my workflow file?
